// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lapushki_api.Data;

#nullable disable

namespace lapushki_api.Migrations
{
    [DbContext(typeof(ContextDb))]
    partial class ContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lapushki_api.Models.Appointments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<int>("doctor_id")
                        .HasColumnType("integer");

                    b.Property<int>("pet_id")
                        .HasColumnType("integer");

                    b.Property<int>("service_id")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("time")
                        .HasColumnType("time without time zone");

                    b.HasKey("id");

                    b.HasIndex("doctor_id");

                    b.HasIndex("pet_id");

                    b.HasIndex("service_id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("lapushki_api.Models.ClinicServices", b =>
                {
                    b.Property<int>("id_service")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_service"));

                    b.Property<int>("duration")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("price")
                        .HasColumnType("double precision");

                    b.HasKey("id_service");

                    b.ToTable("ClinicServices");
                });

            modelBuilder.Entity("lapushki_api.Models.Doctor", b =>
                {
                    b.Property<int>("id_doctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_doctor"));

                    b.Property<int>("duration_slot")
                        .HasColumnType("integer");

                    b.Property<int>("id_user")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("work_end")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("work_start")
                        .HasColumnType("time without time zone");

                    b.HasKey("id_doctor");

                    b.HasIndex("id_user");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("lapushki_api.Models.DoctorService", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("doctor_id")
                        .HasColumnType("integer");

                    b.Property<int>("service_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("doctor_id");

                    b.HasIndex("service_id");

                    b.ToTable("DoctorServices");
                });

            modelBuilder.Entity("lapushki_api.Models.Pet", b =>
                {
                    b.Property<int>("id_pet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_pet"));

                    b.Property<string>("breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id_pet");

                    b.HasIndex("user_id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("lapushki_api.Models.Role", b =>
                {
                    b.Property<int>("id_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_role"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("lapushki_api.Models.User", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_user"));

                    b.Property<DateOnly>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("id_user");

                    b.HasIndex("role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("lapushki_api.Models.Appointments", b =>
                {
                    b.HasOne("lapushki_api.Models.Doctor", "doctor")
                        .WithMany("appointments")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lapushki_api.Models.Pet", "pet")
                        .WithMany("appointments")
                        .HasForeignKey("pet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lapushki_api.Models.ClinicServices", "clinic_service")
                        .WithMany("appointments")
                        .HasForeignKey("service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinic_service");

                    b.Navigation("doctor");

                    b.Navigation("pet");
                });

            modelBuilder.Entity("lapushki_api.Models.Doctor", b =>
                {
                    b.HasOne("lapushki_api.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("lapushki_api.Models.DoctorService", b =>
                {
                    b.HasOne("lapushki_api.Models.Doctor", "doctor")
                        .WithMany("doctor_services")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lapushki_api.Models.ClinicServices", "clinic_service")
                        .WithMany("doctor_services")
                        .HasForeignKey("service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinic_service");

                    b.Navigation("doctor");
                });

            modelBuilder.Entity("lapushki_api.Models.Pet", b =>
                {
                    b.HasOne("lapushki_api.Models.User", "user")
                        .WithMany("pets")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("lapushki_api.Models.User", b =>
                {
                    b.HasOne("lapushki_api.Models.Role", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("lapushki_api.Models.ClinicServices", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("doctor_services");
                });

            modelBuilder.Entity("lapushki_api.Models.Doctor", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("doctor_services");
                });

            modelBuilder.Entity("lapushki_api.Models.Pet", b =>
                {
                    b.Navigation("appointments");
                });

            modelBuilder.Entity("lapushki_api.Models.Role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("lapushki_api.Models.User", b =>
                {
                    b.Navigation("pets");
                });
#pragma warning restore 612, 618
        }
    }
}
